# -*- coding: utf-8 -*-
"""Calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z8_QgICbdHVjNz_YR8IkX2KRuwrPdAWj
"""

a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
while True:
  operator=input("Enter operator(+,-,*,/,**):")
  if operator=="+":
    print(a+b)
  elif operator=="-":
    print(a-b)
  elif operator=="*":
    print(a*b)
  elif operator=="/":
    print(a/b)
  elif operator=="**":
    print(a**b)
  else:
    print("Invalid operator")
    continue

  user=input("Do you want to continue:yes/no")
  if user=="yes":
   continue
  else:
   break